# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuc-mcp" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "d27a6d07b7e422aae90490723c219373e055cf08708e1234026fb38971eb4e15"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5df276314db42ee1bfc2a02e2432f22db2ea293c9d3aa0bd50bddefa600ca796"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "caf5eae90df2e635724c0850a65c23e6dd96787fbb018dd3074e78843f3539df"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4faab994dec2f62713df17a92405196aec43157adc09e8e9f36f463f7bc3623"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nuc-mcp"
  desc "Nucleus Security MCP server — expose vulnerability findings, assets, and scans to AI agents."
  homepage "https://github.com/marstid/nuc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuc-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuc-mcp"]
    end
  end

  # No zap stanza required

end
