# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuc-mcp" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "16c3cdb5587e40ab39abd6321b04670ad88f85e1bb6ca56659f8379ddf8994d0"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "67d828bfb502155a9f089fe86915412df9e485249d11fbfb252042a7a17ef9bc"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "70625e1a52b6bc027ca07c1f3fdb713df9beac82807a3df8cf877e7d57c039da"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc1f3dea7370b0082f7f5a3b96619cb1048cfd9330cdeb7d39b51d14f8f41fc4"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nuc-mcp"
  desc "Nucleus Security MCP server — expose vulnerability findings, assets, and scans to AI agents."
  homepage "https://github.com/marstid/nuc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuc-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuc-mcp"]
    end
  end

  # No zap stanza required

end
