# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuc-mcp" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "d4cbfc6aaa0aafb85c02bbfcbaca64631b237d0ae10c6cb50208200956d0d34b"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be75a37cfe066d95391bcdcd8065b89752a2c72c45abc20f528d2fecf13ca749"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b42229ab8406de2a49fb6ecc41973147de80bd7267e2208242ee8c7e0740542c"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7febc0b70b707590acb1b2ca3f6a0a6025e7895511fac71da8a77031d03d52a"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nuc-mcp"
  desc "Nucleus Security MCP server — expose vulnerability findings, assets, and scans to AI agents."
  homepage "https://github.com/marstid/nuc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuc-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuc-mcp"]
    end
  end

  # No zap stanza required

end
