# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuc" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "7233c59d0f454e6434936b9f8c2fafdfdccf93cd252f7ec6b83608e5b900de9b"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "128ab39f050f36aff11eb28168d754d490f94b7f4c828808da4df28fc8ec5970"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8fa55b4cfb982b89e0a0536ac815b8e891d92983a860b190fa919979c06703b6"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f7b2c600334d47bbf91803c0f4a0febe90f79843b263a02c519e320204a768b"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nuc"
  desc "Nucleus Security CLI — manage vulnerability findings, assets, and scans from the command line."
  homepage "https://github.com/marstid/nuc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuc"]
    end
  end

  # No zap stanza required

end
