# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuc" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "7f6e33ff66cf0d902e2cbb710fe53b2fdf0c781d9dba6e9b16678095ba598a79"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "984e9dc3565c9f55f20d1cbefc1f147c7359d1e87c79210e7a66d828d8da16ef"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99300742ce2d83a2bfac6b09604165f3e51d35e2276eb8f3c5bc53f934bc6c0d"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa30f71ee504f15ec20f0da325e7ec8204c97cf3507a02667e245036d4ca4d58"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nuc"
  desc "Nucleus Security CLI — manage vulnerability findings, assets, and scans from the command line."
  homepage "https://github.com/marstid/nuc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuc"]
    end
  end

  # No zap stanza required

end
