# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuc" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "1466d819bc71e60e02aa258b11d62d66f43a7c87abbd9d743388ed140e128861"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c62f0d6daa8157ce91ec861797bc65c43a75024e4439663f19f63f157f03a0c5"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7dab547ff7a19298d2dec7cb1dfe43a0cd096da1ad91a19ed54605ef2e28b065"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "788fb865ffcff50c6cbf30ba1ef859f17e5993b3d3c0aa2e2a08f91eea96c444"
      url "https://github.com/marstid/nuc/releases/download/v#{version}/nuc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nuc"
  desc "Nucleus Security CLI — manage vulnerability findings, assets, and scans from the command line."
  homepage "https://github.com/marstid/nuc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuc"]
    end
  end

  # No zap stanza required

end
